# Generated by Django 5.1.3 on 2025-08-28 06:22

import django.core.validators
import qr_event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QrIin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "iin",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ИИН должен состоять ровно из 12 цифр.",
                                regex="^\\d{12}$",
                            ),
                            qr_event.models.iin_kz_validator,
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
