# Generated by Django 5.1.3 on 2025-09-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qr_event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qriin",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
