services:
  accreditation-center:
    image: accr-django:latest
    container_name: accr-django
    restart: unless-stopped
    network_mode: "host"
    platform: linux/amd64
    volumes:
      - ./:/app
      - ./media:/app/media
      - ./static:/app/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn eventproject.wsgi:application
               --bind 0.0.0.0:8000
               --workers 4
               --timeout 120"
