# Generated by Django 3.2 on 2022-04-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=20)),
                ("name_kaz", models.CharField(max_length=128)),
                ("name_rus", models.CharField(max_length=128)),
                ("name_eng", models.CharField(max_length=128)),
                ("cis_flag", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Sex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_kaz", models.CharField(max_length=128)),
                ("name_rus", models.CharField(max_length=128)),
                ("name_eng", models.CharField(max_length=128)),
                ("sex_code", models.CharField(max_length=20)),
            ],
        ),
    ]
