# Generated by Django 3.2 on 2022-04-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("directories", "0002_documenttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="country_iso",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
