# Generated by Django 3.2 on 2022-05-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("directories", "0004_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_code", models.CharField(max_length=20)),
                ("index", models.CharField(max_length=20)),
                ("name_kaz", models.CharField(max_length=128)),
                ("name_rus", models.CharField(max_length=128)),
                ("name_eng", models.CharField(max_length=128)),
            ],
        ),
    ]
