# Generated by Django 3.2 on 2022-04-14 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_kaz", models.CharField(max_length=128)),
                ("name_rus", models.CharField(max_length=128)),
                ("name_eng", models.CharField(max_length=128)),
                ("event_code", models.CharField(max_length=20)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patronymic", models.CharField(max_length=128)),
                ("phone_number", models.CharField(max_length=20)),
                ("is_accreditator", models.BooleanField(default=False)),
                ("events", models.ManyToManyField(blank=True, to="eventproject.Event")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("status", models.CharField(max_length=20)),
                ("date_created", models.DateTimeField()),
                ("registration_time", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_operator",
                        to="eventproject.operator",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eventproject.event",
                    ),
                ),
                (
                    "exported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exported_operator",
                        to="eventproject.operator",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=128)),
                ("firstname", models.CharField(max_length=128)),
                ("patronymic", models.CharField(max_length=128)),
                ("birthDate", models.DateField()),
                ("post", models.CharField(max_length=128)),
                ("countryId", models.CharField(max_length=30)),
                ("docTypeId", models.CharField(max_length=30)),
                ("docSeries", models.CharField(max_length=128)),
                ("iin", models.CharField(max_length=12)),
                ("docNumber", models.CharField(max_length=20)),
                ("docBegin", models.DateField()),
                ("docEnd", models.DateField()),
                ("docIssue", models.CharField(max_length=50)),
                ("photo", models.ImageField(blank=True, upload_to="attendee_photos")),
                (
                    "docScan",
                    models.ImageField(blank=True, upload_to="attendee_document"),
                ),
                ("sexId", models.CharField(max_length=20)),
                ("dateAdd", models.DateTimeField()),
                ("visitObjects", models.CharField(max_length=200)),
                ("transcription", models.CharField(max_length=128)),
                ("dateEnd", models.DateField()),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eventproject.request",
                    ),
                ),
            ],
        ),
    ]
