# Generated by Django 3.2 on 2022-05-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventproject", "0005_event_city_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="stickId",
            field=models.CharField(default="", max_length=20),
        ),
    ]
