# Generated by Django 5.1.3 on 2025-09-25 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventproject", "0007_auto_20220604_0731"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="docIssue",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="docNumber",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="iin",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="patronymic",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="post",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="transcription",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="request",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
