# Rollback: python manage.py migrate eventproject 0010_swap_attendee_iin_encrypted
# Generated by Django 5.1.3 on 2026-04-14 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventproject', '0010_swap_attendee_iin_encrypted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported_before', models.DateTimeField(help_text='Граница delta: участники с dateAdd > этого значения считаются новыми')),
                ('attendee_count', models.IntegerField(help_text='Количество участников, включённых в данный экспорт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Категория участников (Request) внутри мероприятия; null = весь event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventproject.request')),
                ('event', models.ForeignKey(help_text='Мероприятие, для которого был выполнен экспорт', on_delete=django.db.models.deletion.CASCADE, to='eventproject.event')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, запустивший экспорт; null для системных/scheduled задач', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
