# Generated by Django 5.1.3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventproject', '0011_exportlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='role',
            field=models.CharField(
                choices=[
                    ('superuser', 'Суперпользователь'),
                    ('superoperator', 'Супероператор'),
                    ('operator', 'Оператор'),
                    ('user', 'Пользователь'),
                ],
                default='operator',
                max_length=20,
            ),
        ),
    ]
