# Generated by Django 5.1.3 on 2026-04-18 16:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventproject", "0012_operator_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Кто создал (Story 2.2)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(
                blank=True, help_text="Описание (Story 2.2)", null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="Дата окончания (Story 2.2)", null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="Дата начала (Story 2.2)", null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title",
            field=models.CharField(
                blank=True, help_text="Заголовок (Story 2.2)", max_length=255, null=True
            ),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Мероприятие (Story 2.2)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="eventproject.event",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attendee",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Категория (Story 2.2)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendees",
                to="eventproject.category",
            ),
        ),
    ]
