# Generated by Django 5.1.3 on 2026-04-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eventproject",
            "0013_event_created_at_event_created_by_event_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="exportlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
