# Generated by Django 5.1.3 on 2026-04-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eventproject",
            "0014_alter_category_created_at_alter_event_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="city_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="name_eng",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="name_kaz",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="name_rus",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
