# Generated by Django 5.1.3 on 2026-06-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventproject', '0015_alter_event_city_code_alter_event_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='credentials_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='email_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('error', 'Error')], default='pending', max_length=20),
        ),
        # default=False: форс смены пароля включается только для авто-созданных
        # операторов (create_operator), существующие строки получают False.
        migrations.AddField(
            model_name='operator',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
