# Generated by Django 5.1.3 on 2026-06-21 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventproject', '0016_operator_credentials_sent_at_operator_email_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators', to='eventproject.category'),
        ),
    ]
