# Generated by Django 5.1.3 on 2026-06-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventproject', '0018_operatoraccessevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='is_resident',
            field=models.BooleanField(default=True),
        ),
    ]
