# Generated by Django 5.1.3 on 2026-06-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventproject', '0019_attendee_is_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('in_review', 'in_review'), ('ready', 'ready'), ('exported', 'exported')], default='draft', max_length=20),
        ),
    ]
