# Generated by Django 5.1.3 on 2026-06-25 06:08
# BE-7 / BE-9: добавляет DB-целостность (уникальность Category, валидность статуса).
# Перед каждым constraint — defensive-чистка существующих данных, чтобы AddConstraint
# не упал на проде (дубли категорий / исторические невалидные статусы).

from django.db import migrations, models

_VALID_STATUSES = ["draft", "submitted", "in_review", "ready", "exported"]


def fix_invalid_statuses(apps, schema_editor):
    # BE-9: любые строки вне FSM-набора → 'draft' (fail-safe), иначе CheckConstraint упадёт.
    Attendee = apps.get_model("eventproject", "Attendee")
    Attendee.objects.exclude(status__in=_VALID_STATUSES).update(status="draft")


def dedupe_categories(apps, schema_editor):
    # BE-7: переименовываем дубли (event, name), сохраняя все строки (без потери данных),
    # чтобы UniqueConstraint можно было добавить. Первую (наименьший pk) оставляем как есть.
    Category = apps.get_model("eventproject", "Category")
    seen = set()
    for cat in Category.objects.order_by("event_id", "name", "id").iterator():
        key = (cat.event_id, cat.name)
        if key not in seen:
            seen.add(key)
            continue
        # Подбираем уникальный суффикс в рамках события.
        n = 2
        base = cat.name
        while (cat.event_id, f"{base} ({n})") in seen:
            n += 1
        cat.name = f"{base} ({n})"[:128]
        cat.save(update_fields=["name"])
        seen.add((cat.event_id, cat.name))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('eventproject', '0022_backfill_attendee_status'),
    ]

    operations = [
        migrations.RunPython(fix_invalid_statuses, noop),
        migrations.AddConstraint(
            model_name='attendee',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'submitted', 'in_review', 'ready', 'exported'])), name='attendee_status_valid'),
        ),
        migrations.RunPython(dedupe_categories, noop),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='uniq_category_event_name'),
        ),
    ]
