# Generated by Django 5.1.3 on 2026-06-26 06:42

from django.db import migrations, models

# Story hd-4.1 (AC-3): append-only на уровне БД. Postgres-триггер ловит сырые
# UPDATE/DELETE в обход ORM (model/manager-guard их не видят). Только Postgres
# (прод, NFR-7 PS.kz); на SQLite-тестах — noop, защита держится на model+manager-guard.
_TRIGGER_SQL = """
CREATE OR REPLACE FUNCTION eventproject_auditlog_append_only()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'AuditLog is append-only: % is forbidden', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER eventproject_auditlog_no_mutate
BEFORE UPDATE OR DELETE ON eventproject_auditlog
FOR EACH ROW EXECUTE FUNCTION eventproject_auditlog_append_only();
"""

_TRIGGER_DROP_SQL = """
DROP TRIGGER IF EXISTS eventproject_auditlog_no_mutate ON eventproject_auditlog;
DROP FUNCTION IF EXISTS eventproject_auditlog_append_only();
"""


def _create_append_only_trigger(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(_TRIGGER_SQL)


def _drop_append_only_trigger(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(_TRIGGER_DROP_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('eventproject', '0024_recompute_is_resident'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.PositiveIntegerField(blank=True, help_text='Снимок id актора (НЕ FK — append-only аудит хранит историческую ссылку; удаление User не трогает журнал). null для system/Celery', null=True)),
                ('role', models.CharField(max_length=32)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('obj_type', models.CharField(max_length=64)),
                ('obj_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['obj_type', 'obj_id'], name='eventprojec_obj_typ_f74edf_idx')],
            },
        ),
        migrations.RunPython(_create_append_only_trigger, _drop_append_only_trigger),
    ]
