# Generated by Django 5.1.3 on 2026-06-26 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventproject', '0025_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_container',
            field=models.BooleanField(default=False, help_text='True = контейнер (есть под-мероприятия); участники крепятся только к листу (hd-5.2)'),
        ),
        migrations.AddField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Родительское мероприятие-контейнер; NULL = самостоятельное/контейнер. Один уровень (hd-5.1)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subevents', to='eventproject.event'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('parent__isnull', True), models.Q(('parent', models.F('id')), _negated=True), _connector='OR'), name='event_no_self_parent'),
        ),
    ]
