# Generated by Django 5.1.3 on 2026-06-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventproject', '0026_event_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='problem_flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
