# Generated by Django 5.1.3 on 2026-06-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventproject", "0028_backfill_problem_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="last_return_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendee",
            name="return_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
